# Site settings
title: The Bitcoin Association of Hong Kong
location: Hong Kong
description: "Fostering and promoting Bitcoin and its technology in Hong Kong."
baseurl: ""
url: "https://www.bitcoinhk.org"

# More settings
accent: "#E74C3C"
twitter: "none"
github: "bitcoinhk/bitcoinhk.github.io"
contact: "info at bitcoinhk dot org"
organizers: "The Community"

# Get Meetup Notifications, visible or hidden
notifications: "visible"


# Build settings
markdown: kramdown
permalink: pretty

prose:
  rooturl: '_posts'
  siteurl: 'https://www.bitcoinhk.org/'
  media: 'media'
  ignore:
    - index.html
    - meetups.html
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "select"
          options:
            - name: 'meetup'
              value: 'meetup'
            - name: 'blog'
              value: 'blog'
      - name: "meetup"
        field:
          element: "hidden"
          value: "meetup"
      - name: "categories"
        field:
          element: "select"
          options:
            - name: 'meetup'
              value: 'meetup'
            - name: 'blog'
              value: 'blog'
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
      - name: "date"
        field:
          element: "text"
          label: "Date (YYYY-MM-DD HH:MM:SS)"
          value: "2014-06-08 10:30:00"
      - name: "host"
        field:
          element: "text"
          label: "Host"
          value: ""
      - name: "address"
        field:
          element: "text"
          label: "Address"
          value: ""
      - name: "link"
        field:
          element: "text"
          label: "Link"
          value: ""
      - name: "background"
        field:
          element: "text"
          label: "Background (CSS)"
          value: "url() #03152A"
